### ISSUE TITLE
dev environment

### ISSUE THREAD

**Issue by qtsky89** [qtsky89/fastapi#2]
## Issue
* keep continue to read documents in fastapi website
* https://fastapi.tiangolo.com/lo/python-types/

**Comment by qtsky89** [comment]
## Todo
* [x] https://fastapi.tiangolo.com/tutorial/path-params
* [x] https://fastapi.tiangolo.com/tutorial/query-params/
* [x] https://fastapi.tiangolo.com/tutorial/body/
* [x] https://fastapi.tiangolo.com/tutorial/query-params-str-validations/
* [x] https://fastapi.tiangolo.com/tutorial/path-params-numeric-validations/
* [x] https://fastapi.tiangolo.com/tutorial/body-multiple-params/
* [x] https://fastapi.tiangolo.com/tutorial/body-fields/
* [x] https://fastapi.tiangolo.com/tutorial/body-nested-models/
* [x] https://fastapi.tiangolo.com/tutorial/schema-extra-example/
* [x] https://fastapi.tiangolo.com/tutorial/extra-data-types/
* [x] https://fastapi.tiangolo.com/tutorial/cookie-params/

**Comment by qtsky89** [comment]
## Memo
* [ ] https://fastapi.tiangolo.com/tutorial/dependencies/
